[package]
name = "risczero-zkvm-benchmark-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[build-dependencies]
risc0-build = "0.11"

[dependencies]
risc0-zkvm-guest = "0.11"
risc0-zkp = { version = "0.11", default-features = false }
