[package]
name = "risczero-benchmark-methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
blake3 = { version = "1.4", default-features = false }
risc0-zkvm = { version = "0.18", default-features = false, features = ["std"] }
