[package]
name = "risczero-benchmark-methods"
version = "0.1.0"
edition = "2021"

[build-dependencies.risc0-build]
version = "1.0.0-rc.2"
git = "ssh://git@github.com/risc0/risc0.git"
default-features = false

[package.metadata.risc0]
methods = ["guest"]
